ufosc/Echo-Chat

- client/App.tsx
- client/package-lock.json
- client/package.json
- client/src/components/DisplayLocation.tsx
- client/src/components/ProximityChat.tsx
- client/src/constants/LocationContext.tsx
Will be easier to add components that can read the location now
> Refactored location to a context

- client/src/constants/scripts.ts
> Switched var colors in scripts.ts to adjectives and added more

- README.md
- server/.gitignore
- server/config_example.md
- server/package-lock.json
- server/package.json
- server/src/actions/getMessages.ts
- server/src/index.ts
- server/src/scripts/firebaseInit.ts
- server/src/types/Message.ts
I've made a project structure that should scale well with creating many CRUD operations. Firebase was able to be connected too and data was able to be retrieved inside of a collection.
I'll create documentation for how to set up collections on Firebase's website, since they have to match the appearance of their respecting type in /server/src/types.
The configuration for Firebase (API keys, tokens, etc) are also being placed in an .env file. The parameters for this are specified in config_example.md.
> Improved directory structure of /server and created connection to Firebase.

- client/App.tsx
- client/package-lock.json
- client/package.json
- client/src/components/DisplayLocation.tsx
- client/src/components/Message.tsx
- client/src/components/MessageBox.tsx
- client/src/components/MessageList.tsx
- client/src/components/ProximityChat.tsx
- client/src/constants/types.ts
- client/tsconfig.json
I'm not sure how this worked on my desktop, but it works again
> Fixed missing closing bracket

- server/src/actions/getMessages.ts
- server/src/index.ts
- server/src/utilities/broadCoordsCalculation.ts
> initiated broad coordinate calculations

- server/package-lock.json
- server/package.json
- server/src/index.ts
- server/src/utilities/broadCoordsCalculation.ts
- server/src/utilities/coordinateBoundariesCalculation.ts
> Implemented coordinateBoundariesCalculation and testing

- client/package-lock.json
- server/src/actions/getMessages.ts
- server/src/actions/getUsers.ts
- server/src/index.ts
Changed names and lat lon positions
Added:
- broad coordinates endpoint to the second decimal point
> added new unit test endpoints

- ApiChecklist.md
- server/src/actions/createMessage.ts
- server/src/actions/getMessages.ts
- server/src/index.ts
- server/src/types/Message.ts
- server/src/types/User.ts
- server/src/utilities/firebaseInit.ts
- Finished /messages?broadLat=<broadLat>&broadLon=<broadLon>&timeFrame=<timeFrame>
- Created Users type
> Finished features #4 and started on user features

- server/src/utilities/calculateCoordinateBoundaries.ts
Basically a walkthrough of the thought process
> Added detailed explanation/clarification on how we calculate our specific coordinates

- server/src/actions/createUsers.ts
- server/src/actions/updateUser.ts
- server/src/index.ts
Changelog:
- createUsers now works (check index.ts for endpoint)
- updateUsers now works (check index.ts for endpoint)
- updateUsers can only update user location right now
- cleaned up and also made error catchers
- Let me know if you have questions
Thanks, Alex!
> New endpoints and users are now added!

- server/src/actions/createMessage.ts
- server/src/actions/getMessages.ts
- server/src/index.ts
Made whitespace more consistent from the last few PRs and added in some task comments.
> Readability updates

- client/src/components/MessageBox.tsx
- IOS: Keyboard now follows text input on click (ios only)
- Input remodeled and optimized using flex
Bugs:
- Input size grows and shrinks when typing LOL (will fix soon)
Todos:
- Fix all bugs
- Make spacing between MessageList and MessageBox (input) a bit bigger
- Testing on Android
> keyboard padding on focus + changed input

- client/src/components/MessageList.tsx
added random message
hi im adi! nice to meet you guys! ૮ ˶ᵔ ᵕ ᵔ˶ ა
> onboarding test

- README.md
- client/src/components/MessageBox.tsx
- server/src/index.ts
> Add port to env

- client/App.tsx
- client/package-lock.json
- client/package.json
- client/src/components/MessageWrapper.tsx
- client/src/components/ProximityChat.tsx
- client/src/constants/SocketContext.tsx
- server/package-lock.json
- server/package.json
- server/src/index.ts
Work in progress
Connected backend and fronted using socket.io!
Check docs for more info!
> Added Socket.io and successfully connected

- server/src/actions/getMessages.ts
- server/src/index.ts
Changes:
- Added message socket connection call
- Uncommented and restructured some REST calls
> Added messaging functionality to Socket Backend

- client/src/components/Chat/ChatScreen.tsx
Trimmed the excess whitespace at the beginning and end of messages.
> Excess whitespace trimming

- server/src/actions/createMessage.ts
- server/src/actions/createUser.ts
- server/src/actions/deleteUser.ts
- server/src/actions/pushMessage.ts
- server/src/actions/updateUser.ts
- server/src/index.ts
- server/src/tests/RestApiTests.sh
- server/src/tests/socketio.test.ts
- server/src/types/User.ts
- server/src/utilities/firebaseInit.ts
Firestore User documents can now be created, modified and deleted via new functions included in `actions`.
For the User type, a new `isConnected` attribute has been added as well. toggleUserConnectionStatus() can work with this attribute for both logistical and moderation purposes (e.g. setting it to `false` to kick a user).
For sockets, when a new user connects, a new user document will be created in Firestore using the socket id as the user id. This document is deleted when the user disconnects. Location can be updated via updateUserLocation() given `userId`, `lat`, and `lon` parameters. The user's geohash will also be calculated and stored from this function.
> Integration of User CRUD operations into REST and socket Apis

- client/babel.config.js
- client/package-lock.json
- client/package.json
- client/src/app/index.tsx
- client/src/components/Auth/LoginScreen.tsx
- client/src/configs/firebaseConfig.ts
- client/src/services/store.ts
For issue #68 
Added firebase authentication and the log in feature.
Changelog:
- Fixed .env for firebase authentication
- Added error catching for multiple firebase app initilizations
- Create a sign in example that moves to ChatScreen after logging in
Issues:
- Need a sign out screen
- Need a Log in screen
> Fixed and added Firebase Auth

- client/.gitignore
- client/src/components/Auth/SignUpScreen.tsx
These are the changes that were supposed to be in my previous PR, but I accidentally merged it before adding them.
> Removed firebaseConfig from gitignore

- client/src/contexts/SocketContext.tsx
Closes #106 
Due to initial confusion with Git workflows and repository management, I have set up a fresh fork and reimplemented the automated IP address retrieval feature for the SocketContext.tsx.
> Automate IP address retrieval for socket connection.

- server/src/actions/getUsers.ts
- server/src/index.ts
- server/src/tests/socketio.test.ts
- server/src/types/Message.ts
Closes #60 
Message sending with sockets broke recently from not including the generated hash, which has now been fixed.
Also fixed test case 4, which now works consistently. Test cases have also been cleaned up.
Socket message/ping acknowledgments will also only run if requested, to prevent errors.
> Improve "Send message to user" test case and various bugfixes

- server/src/_deprecatedActions/createUser.ts
- server/src/_deprecatedActions/deleteMessage.ts
- server/src/_deprecatedActions/deleteUser.ts
- server/src/_deprecatedActions/getMessages.ts
- server/src/_deprecatedActions/getUsers.ts
- server/src/_deprecatedActions/updateUser.ts
Closes #116 
Changelog:
Commented out all the code in deprecated folder in server side. This allows us to compile in watch mode without any errors now!
> Commented out Deprecated Actions in Backend

- server/package-lock.json
- server/package.json
- server/src/actions/getUsers.ts
- server/src/index.ts
- server/src/tests/socketio.test.ts
Changelog:
Added multiple clients connecting to backend sockets (as many as you choose) to check load tests
You can also mess around and add more tests along with those clients.
Be sure not to go over say 300 clients or firebase might actually start rejecting you due to too many requests.
Also added jest.timeout to 1 minute so it doesn't time you out after only a few seconds!
> Added load testing to Jest Tests

- client/config_example.md
- server/config_example.md
- server/src/utilities/firebaseInit.ts
Updated the variable cases in the `./client/config_example.md` file to match those of the corresponding file in the server size. Please follow this up with a new issue regarding fixing the corresponding problem in the documentation.
Fixes #119
> Updated client/config_example.md to be consistent with backend

- client/config_example.md
Changelog:
- Changes Config_example.MD with new values needed for running expo with backend
> Updates Config_Example.MD with new values

- client/src/components/Auth/AuthenticationResponse.tsx
- client/src/components/Auth/SignUpScreen.tsx
Password confirm box was re-added, and a bug was fixed where a new account would be created when passwords still didn't match.
> Fixed password confirm box.

- client/src/components/Settings/SettingsItem.tsx
- client/src/components/Settings/SettingsScreen.tsx
Added a mock setting screen with "toggle" and "select" settings types.
Still needs to be modified to use icons instead of an image for the right arrow and to make the switches interact with the real settings values.
> Settings screen

- client/src/components/Auth/AuthenticationResponse.tsx
- client/src/contexts/LocationContext.tsx
Cleaned up parent useEffect function using return and displaying message to console, indicating location is reset. Phone still heats up while signed in, most likely due to the frequency of updating location. Closes #159
> Cleaned location use effect

- server/src/types/Message.ts
> Update message type to reflect users it is visible to

- server/src/actions/deleteConnectedUser.ts
- server/src/actions/getConnectedUsers.ts
- server/src/actions/updateConnectedUser.ts
- server/src/index.ts
- server/src/routes/error/error.ts
- server/src/routes/user/create.ts
- server/src/routes/user/delete.ts
- server/src/routes/user/nearby.ts
- server/src/routes/user/update.ts
For #266
Certain invalid API routes were incorrectly handled, leading to a response never being sent to the client. Additionally, the sent error responses usually didn't have specific status codes (defaulting to `200` for anything besides page-not-found errors).
I addressed these issues by refactoring the `actions` used by the affected API routes to make them easier to deal with and then refactoring the Express routes themselves (mostly in `routes/user`) to return specific `400` and `500` error codes. I also had to change how some actions were called from the socket API in `index.ts` because of the action refactors.
I tried to keep everything compliant with the tests in `express.test.ts` (and they do still pass); however, it seems like there are separate issues with the tests causing them …
> Refactored Express API Routes

- client/app/screens/settings/SettingsScreen.tsx
This PR updates the settings screen and it handles with issue no. #281
> fix: Changed to Delete my messages when I dissapear

- client/assets/theme.ts
> added Theme.ts file which contains all the hex values of the majors colors that are used

- client/app/navigation/AppNavigator.tsx
Issue #317 The bottom tab bar is now hidden when users choose to type a message.
> Hid Tab Bar when typing

- client/app/components/chat/NearbyHeader.tsx
- client/app/navigation/AppNavigator.tsx
**Changes:**
- Addressed issue #318 
- Adjusted position of nearby user count relative to icon
- Adjusted height of Nearby text
> Updated NearbyHeader UI

- client/app/navigation/AppNavigator.tsx
Resolves #331
- Changed navigation tab titles from "Home" and "Profile" to "Chat" and "Settings" and updated their Icons.
> Update to the navigation tab

- client/app/components/auth/LargeTextButton.tsx
- client/app/screens/auth/LoginScreen.tsx
- client/app/screens/auth/SignUpScreen.tsx
Resolves #327  
- Added a loading spinner to both the sign-up and login buttons while a user is waiting to be authenticated.  
https://github.com/user-attachments/assets/4d2b883c-476d-4155-a170-dcbf55cc12d7
> Added Loading Spinner for Sign Up and Login

- README.md
I changed the wording of some sections to become more informative as well as include a helpful table of contents and added different sections to become more transparant with potential users and contributors in the future.
> Update README with table of contents, features, roadmap; wording updates on various sections
