server/package.json
server/src/actions/createMessage.ts
server/src/actions/getMessages.ts
server/src/index.ts
server/src/types/Message.ts
server/src/utilities/firebaseInit.ts
server/tsconfig.json

Updated GET request to /messages to now return a JSON object with the message data instead of just printing to the console as a proof of concept. POST request to /messages/new will also create a new message document in Firebase.
I also renamed /server/src/scripts to /server/src/utilities since I thought the naming would make more sense.

Improve /server API routes

---

server/package.json

Since `nodemon` is already installed on the server side, I thought that it's better to use it to run the application locally as there is a hot reload feature which makes debugging easier.

Switch from node to nodemon to run app locally

---

ApiChecklist.md
server/src/actions/createUser.ts
server/src/actions/deleteMessage.ts
server/src/actions/deleteMessages.ts
server/src/actions/deleteUser.ts
server/src/actions/getMessages.ts
server/src/actions/getUsers.ts
server/src/index.ts
server/src/types/User.ts

* Endpoints for `DELETE /messages?msgId=<msgId>`, `GET /users?userId=<userId>`, `DELETE /users?userId=<userId>` have been added
* Endpoint for `POST /users` has been updated
This PR finishes the rest of the routes specified in ApiChecklist. Logic has been added for deleting documents in Firebase, however there is a bug where we won't actually know if a particular document has been actually deleted or not. I attempted to circumvent this by checking to see if a requested document exists in the database before deleting it, which prevents this issue to a much greater capacity, but not completely since the `deleteDoc()` function provided by Firestore can still technically fail. Further research should be done in the security of the delete actions especially if the app starts to scale. Further …

[Back-end] Added multiple endpoints for /messages and /users

---

client/src/components/Common/NearbyCount.tsx
client/src/components/Common/NearbyHeader.tsx

Closes #115
I have duplicated the type for the count props in the child component as well. I'm thinking that we should store the types for all the props associated with the different components in a seperate folder of its own so that the design is cleaner.

Modularize NearbyHeader component

---

client/app.json
client/package-lock.json
client/package.json
client/src/app/(home)/_layout.tsx
client/src/contexts/LocationContext.tsx
client/src/contexts/SocketContext.tsx

Closes #86 
Changlog:
- Added Location Context for Location Retrieval
- Fixed up Socket Context to use with EXPO's local IP.
- Added error checking and ack() into socket context when emitting!
After a few months of trying, the frontend and the backend have finally been connected!
Some tips: Location is set to highest due to testing, will most likely be on low for actual production!
Contexts are very intertwined!!! :star:

Enabled Location Data gathering and also connecting sockets between Client and Server

---

client/src/components/Auth/LoginScreen.tsx
client/src/components/Common/CustomInputs.tsx

Added a prop to ChatInputProps so that when appSignIn returns error, the text inputs for LogInEmailInput and LogInPasswordInput will have a red border.

Added red borders to the Text Input on the Login Screen when the Authentication fails

---

client/src/components/Chat/ChatScreen.tsx
client/src/components/Common/ChatMessage.tsx
client/src/components/Common/MessageChannel.tsx
client/src/contexts/LocationContext.tsx
client/src/contexts/SettingsContext.tsx
client/src/contexts/SocketContext.tsx
client/src/types/Message.ts
client/src/utils/types.ts
server/src/index.ts
server/src/tests/socketio.test.ts

This PR re-adds echologation while utilizing websockets and our new database schemas.
The location and socket contexts are used within ChatScreen.tsx, as well as the AuthStore to retrieve the UID of the logged in user.
Some issues I found while working on this include some poor functionality segmentation within these contexts (ie. some things within the context useEffects should be moved to functions in seperate files), a problem with the location refreshing (entire app needs to be closed out since the loop never stops). Appropriate FIXMEs and READMEs have been put within these files, and future issues will be made shortly.
A bug was also fixed to display time correctly on each message (the current time used to be displayed on all of them), and testing has been updated to be consistent …

Integrate client-server message sending and retrival

---

client/src/components/Auth/AuthenticationResponse.tsx

Closes #148 
Made error case for email already in use display on the front end.

Email in use error case

---

.github/workflows/main.yml
server/src/tests/socketio.test.ts

Description:
- Adding jest test pipeline to unit test before merging

Added testing pipeline

---

server/package-lock.json
server/package.json
server/src/index.ts

Resolves #164.
Encountered a couple of issues implementing this, mostly due to the Mailgun docs.
Relevant issues:
1. https://github.com/mailgun/mailgun.js/issues/220
2. https://github.com/mailgun/mailgun.js/issues/269.
The FormData object used by the `Mailgun` constructor should be [the FormData Web API](https://developer.mozilla.org/en-US/docs/Web/API/FormData) and not the FormData object made available through the [`npm` dependency](https://www.npmjs.com/package/form-data). The import used within the Mailgun guide is thus unnecessary. 
Currently, the emails sent using Mailgun ends up in the spam folder, so that is something we can maybe look into in the near future. The email addresses that we are sending to should be added to the [Authorized …

Send verification email using Mailgun

---

client/src/components/Chat/ChatScreen.tsx
client/src/components/Common/MessageChannel.tsx
client/src/types/Message.ts
server/.gitignore
server/src/actions/calculateDistance.ts
server/src/index.ts
server/src/types/Message.ts
server/src/utilities/firebaseInit.ts

Changed from message trigger to incoming messages. This allows us to scale to other features easier such as reaction or really anything else. The lag is not that much different and we will implement a greyed out pending message on the user side!
Unit tests will have to be updated to reflect these changes!

Switched to publish subscribe model for messages

---

client/src/components/Chat/ChatScreen.tsx
client/src/components/Common/MessageChannel.tsx
client/src/types/Message.ts
server/.gitignore
server/package-lock.json
server/package.json
server/src/actions/calculateDistance.ts
server/src/actions/deleter.ts
server/src/index.ts
server/src/types/Message.ts
server/src/utilities/firebaseInit.ts

Cron-job for message deletion has now been implemented. The current deletion interval is set to 30s for development and testing purposes. 
In addition, there is now a new `.env` variable that is required to be created: `message_duration`. Set it to 60000 for now.
Also, added `firebase-secrets.json` to the `.gitignore` to avoid it getting tangled up in commits.
Fixes #157.

Implemented cronjob for message deletion

---

client/src/services/SettingsStore.ts

Closes #213 
Replaces SettingsContext with SettingsStore within the services folder which can be used to retrieve dark mode or light mode and toggle between them within the settings screen. Uses pullstate.

Added settings pullstate and settings store

---

server/src/utilities/firebaseInit.ts

Tried setting up the project again and I found a typo in this path when comparing against the documentation in server/config_example.md.

typo in path

---

client/app/screens/chat/ChatScreen.tsx
client/app/screens/settings/SettingsScreen.tsx

Yeah boy. I fixed it. Lets go.
Fixes #229

Fixed key error for settings page

---

client/app/screens/settings/SettingsScreen.tsx
server/.gitignore
server/src/index.ts
server/src/utilities/firebaseInit.ts

Before it would pull every message that ever existed. Now it limits that query to 1 message.

Observer fix to limit retrieve messages

---

client/app/components/auth/AuthButtons.tsx

I just removed the function that imports fonts. It was not needed since the there is already a global function declaration in **index.js**. 
This repeat declaration was only found in one component and not in any of the other folders within the client/ directory.

removed function that imported fonts || Issue #242

---

README.md

Can you please let me know any issues in this , I will try to fix it.

added Figma file link to README.md file

---

client/app/configs/firebaseConfig.ts
client/config_example.md

Unwanted variable changes.  Removed the variables which were not needed as per mentioned in the issue.
Fixes #244

Remove useless variables

---

server/.gitignore
server/config_example.md
server/src/index.ts

It's not completely fixed yet but I discovered that the backend would crash when a new user connected due to an invalid attribute for Observer in index.ts. I've fixed it so that the app doesn't crash now, but for some reason message retrieval doesn't work for me. I may create an issue for this.
For the same function I also added two default env parameters for limiting message retrieval. Notes these aren't really tested because message retrieval currently doesn't seem to work.
Also made an addition to the backend gitignore in case of a misunderstanding of the documentation.

Backend hotfixes

---

client/app/components/settings/TextInputs.tsx
client/app/screens/settings/SettingsScreen.tsx

For #259. Adds a profile picture to the settings screen. Clicking on the picture opens/closes a menu to set the display name, profile picture, and profile picture background color.

Add profile settings menu

---

client/app/configs/firebaseConfig.ts
client/app/services/AuthStore.ts
client/config_example.md

**Description**
This PR adds the functionality to automatically create a UserConfig document in Firebase Firestore after a user signs up in the app.
**Key Changes:**
- A new method createUserConfig has been added to the AuthStore.ts class.
- After user signup, createUserConfig is called, which creates a UserConfig document in Firestore for the newly registered user.
- The UserConfig collection is initialized with the following default fields:
- darkMode: false (indicating that dark mode is disabled by default)
- notificationsEnabled: false (indicating that notifications are disabled by default)
- language: 'English' (default language setting)
This ensures that each new user has a personalized configuration stored, which can be updated later according to user preferences.

Create UserConfig Collection after User Signup

---

server/src/actions/calculateDistance.ts
server/src/index.ts
server/src/types/Location.ts
server/src/types/User.ts

I've roughly ported the distance check implementation from Prox.
It adds an equirectangular approximation for checking distances less than 1.5 km. Above which, the accuracy begins to drift significantly. If we ever need to check larger distances, the haversine distance equation (previous default) will be used.
This saves multiple resource intensive sqrt and trig operations reducing load on the server without loosing functionality.

Distance Check Approximation

---

client/app/components/chat/ChatScreenFooter.tsx

- Adjusted `ChatScreenFooter.tsx` styles to vertically align the send button with the TextInput placeholder text.
- Verified alignment on both Android
Closes #320

Fix: Align send button with chat TextInput default text (Closes #320)

---

client/app/services/SocketService.ts

This is going to sound insane but
For some reason I cannot get a client device to connect without the SOCKET environment variables being printed to console. There is probably a better solution than this, but to keep things working easily for most people for now I am adding this.

Added a console.log

---

client/app/components/chat/MessageChannel.tsx
client/app/screens/chat/ChatScreen.tsx
client/app/services/SocketService.ts
client/app/types/Message.ts
client/app/types/Props.ts
server/src/socket_server/methods/send_message.ts
server/src/types/message.ts

For issue #232 
This PR refactors the messages state on the client (in `<ChatScreen />`) from an array (`Message[]`) to a Map with message IDs as keys (`Map<string, Message>`). To do this, I also had to add a message ID attribute using a UUID generated with `expo-crypto`. The messages map is passed to `<MessageChannel />` as a map, which is then converted/sorted inside `<MessageChannel />` on render.
For future improvements, it may be a good idea to persist a sorted array on the client in addition to the map, so that it does not have to be created and sorted on every rerender. This is not a big problem for now but may introduce some performance costs when scaling to large and quickly updating chats. A hybrid approach may allow for the best of both data structures.
It should also be noted …

Refactored messages Array on client to use a Map
